name: Generate ASCII Workflow

on:
 push

jobs: 
  build_job_1:
    runs-on: ubunntu:latest
    steps:
    - name: Install Cowsay Program
      run: sudo apt-get install cowsay -y

    - name: Execute Cowsay CMD
      run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt

    - name: Sleep for 30 Seconds
      run: sleep 30
    
  test_job_2:
    runs-on: ubunntu:latest
    steps:
    - name: sleep for 10 seconds
      run: sleep 10

    - name: Test File Exists
      run: grep -i "dragon" dragon.txt

  deploy_job_3:
    runs-on: ubunntu:latest
    steps:
    - name: Read File
      run: cat dragon.txt

    - name: Deploy 
      run: echo Deploying
    
      