name: Exploring variables & Secrets

on:
    push
#charan63
env:
    CONTAINER_REGISTRY: docker.io
    IMAGE_NAME: github-actions-nginx
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker build
        run: docker build -t $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

      - name: Docker Login
        run: docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
        
      - name: Docker Publish
        run: docker push $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

  Deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Docker Run
        run: docker run -d -p 8080:80 $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

